### PR TITLE
interp: fix assign of function values with binary methods

### LINKED ISSUE #1145: assign a function value with a binary method
The following program `sample.go` triggers an unexpected error:

```go
package main

import "sync"

type F func()

func main() {
    var wg sync.WaitGroup
    var f F = wg.Done
    println(f != nil)
}   
```

Expected result:
```console
$ go run ./sample.go
true
```

Got:
```console
$ yaegi ./sample.go
run: /Users/marc/sample.go:9:12: cannot use type  as type main.F in assignment
```

### PR DESCRIPTION
**Pull request by mvertes**
In typecheck.go, detect binary methods so we know when to skip the receiver as first parameter when checking function signatures. The signature check is not yet performed, we just avoid a false error.

In cfg.go, take care to label types with isBinMethod field to true whenever a binary method is resolved.

Also, do not attempt to wrap node in functions if the node value is already a binary function.

Fixes #1145.

### CODE REVIEW

File: interp/value.go [hunk 1]
```diff
@@ -157,7 +157,12 @@ func genValueAsFunctionWrapper(n *node) func(*frame) reflect.Value {
 		if v.IsNil() {
 			return reflect.New(typ).Elem()
 		}
-		return genFunctionWrapper(v.Interface().(*node))(f)
+		vn := v.Interface().(*node)
+		if vn.rval.IsValid() && vn.rval.Type().Kind() == reflect.Func {
```
Comment (mpl) [inline interp/value.go:161]: Is it useless to instead do:
```suggestion
		vn, ok := v.Interface().(*node)
		if ok && vn.rval.IsValid() && vn.rval.Type().Kind() == reflect.Func {
```
?

**Review by mpl — APPROVED** [review]
