### PR TITLE
fix: correct handling of select comm clause with empty body

### LINKED ISSUE #887: Select statement does no proceed if no body statements given
The following program `sample.go` demonstrates the problem:

```go
package main

import (
	"time"
)

func main() {
	t := time.NewTicker(time.Second)
	defer t.Stop()

	ch := make(chan struct{})
	defer close(ch)

	for i := 0; i < 3; i++ {
		println("here")

		select {
		case <-ch:
			return
		case <-t.C:
		}
	}
}
```

Expected result:
```console
$ go run ./sample.go
here
here
here
```

Got:
```console
$ yaegi ./sample.go
here
```

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #887.

### CODE REVIEW

File: _test/select14.go [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+
+func main() {
+	t := &T{}
+	t.c2 = make(chan string)
+
+	go func(c chan string) { c <- "done" }(t.c2)
+
+	select {
+	case msg := <-t.c1:
+		println("received from c1:", msg)
```
Comment (mpl) [inline _test/select14.go:16]: Is this case useful for the test?

Comment (mvertes) [reply _test/select14.go:16]: It makes sense to have multiple comm clauses to test for correct branching, at CFG level and at run level.

**Review by mpl — APPROVED** [review]
