### PR TITLE
interp: add support for binary composite slice

### LINKED ISSUE #987: automatic type in literal composite
The following program `sample.go` triggers an unexpected error:

```go
package main

import (
    "fmt"
    "net/url"
)

func main() {
    body := url.Values{
        "Action": {"none"},
    }   
    fmt.Println(body)
}   
```

Expected result:
```console
$ go run ./sample.go
map[Action:[none]]
```

Got:
```console
$ yaegi ./sample.go
./sample.go:14:13: undefined type
```

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #987.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -2213,6 +2213,51 @@ func compositeBinMap(n *node) {
...
+	value := valueGenerator(n, n.findex)
+	next := getExec(n.tnext)
+	child := n.child
+	if n.nleft == 1 {
+		child = n.child[1:]
+	}
+
+	values := make([]func(*frame) reflect.Value, len(child))
+	index := make([]int, len(child))
+	rtype := n.typ.rtype.Elem()
```
Comment (mpl) [inline interp/run.go:2226]: Maybe we also need the part here to handle the cases for a slice of pointers, like in doCompositeBinStruct:

	if n.typ.cat == ptrT || n.typ.cat == aliasT {
		rtype = n.typ.val.rtype
	}

?

**Review by mpl — APPROVED** [review]
