### PR TITLE
interp: detect invalid uses of _ as value

### LINKED ISSUE #1386: Assigning blank to blank causes a panic
### The following program `sample.go` triggers an unexpected result

```go
interp.Eval("_ = _")
```

### Expected result

```console
Not a panic
```

### Got

```console
panic: 1:32: incomplete type _ [recovered]
        panic: 1:32: incomplete type _

goroutine 18 [running]:
testing.tRunner.func1.2({0xd80820, 0xc000120648})
        /usr/local/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1212 +0x218
panic({0xd80820, 0xc000120648})
        /usr/local/go/src/runtime/panic.go:1038 +0x215
github.com/traefik/yaegi/interp.(*itype).refType(0xc00044dc20, 0xca3d60)
        /home/firelizzard/src/yaegi/interp/type.go:1748 +0x1425
github.com/traefik/yaegi/interp.(*itype).TypeOf(...)
        /home/firelizzard/src/yaegi/interp/type.go:1870
github.com/traefik/yaegi/interp.genDestValue(0xc00044dc20, 0xc00043b7a0)
        /home/firelizzard/src/yaegi/interp/value.go:220 +0x29
github.com/traefik/yaegi/interp.assign(0xc00043b560)
        /home/firelizzard/src/yaegi/interp/run.go:662 +0x1fe
github.com/traefik/yaegi/interp.setExec.func1(0xc00043b560)
        /home/firelizzard/src/yaegi/interp/cfg.go:2584 +0x1f6
github.com/traefik/yaegi/interp.setExec(0xc00043b560)
        /home/firelizzard/src/yaegi/interp/cfg.go:2587 +0xfd
github.com/traefik/yaegi/interp.(*Interpreter).CompileAST(0xc00043c240, {0xf52558, 0xc0004db590})
        /home/firelizzard/src/yaegi/interp/program.go:96 +0x27e
github.com/traefik/yaegi/interp.(*Interpreter).compileSrc(0xc00043c240, {0xdad7da, 0x1f}, {0x0, 0x1f}, 0xff)
        /home/firelizzard/src/yaegi/interp/program.go:52 +0xb8
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc00043c240, {0xdad7da, 0x0}, {0x0, 0x0}, 0x0)
        /home/firelizzard/src/yaegi/interp/interp.go:606 +0x28
github.com/traefik/yaegi/interp.(*Interpreter).Eval(...)
        /home/firelizzard/src/yaegi/interp/interp.go:492
github.com/traefik/yaegi/interp.TestGlobals(0xc000102820)
        /home/firelizzard/src/yaegi/interp/interp_test.go:205 +0x19e
testing.tRunner(0xc000102820, 0xdf8f28)
        /usr/local/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1306 +0x35a
FAIL    github.com/traefik/yaegi/interp 0.010s
```

### Yaegi Version

5665c9a4108e5f878c0d1d8d1e1913eb3c314154

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by mvertes**
We now detect the use of special identifier _ (blank) during parsing in order to abort compiling early. It allows to not panic later during execution. We must catch all the cases where blank is used as a value, but still preserve the cases where it is assigned, used as a struct field or for import side effects.

Fixes #1386.

### CODE REVIEW

File: interp/cfg.go [hunk 1]
```diff
@@ -877,6 +898,12 @@ func (interp *Interpreter) cfg(root *node, sc *scope, importPath, pkgName string
 			gotoLabel(n.sym)
 
 		case callExpr:
+			for _, c := range n.child {
+				if isBlank(c) {
+					err = n.cfgErrorf("cannot use _ as value")
+					return
```
Comment (mpl) [inline interp/cfg.go:904]: I know you used a return because a break would only get us out of L906, but now I'm wondering if we should not change all the breaks (like L785) in returns (even though it's not necessary) to show the same intent everywhere.
But it can be in another PR.

**Review by mpl — APPROVED** [review]
