### PR TITLE
interp: improve handling of aliased types

### LINKED ISSUE #1068: aliased interface
The following program `sample.go` triggers a panic:

```go
package main

type I interface {
    Hello()
}

type T struct{}

func (t T) Hello() { println("hello") }

type I2 I

func main() {
    var i I2 = T{}
    i.Hello()
}
```

Expected result:
```console
$ go run ./sample.go
hello
```

Got:
```console
$ yaegi ./sample.go
/Users/marc/sample.go:15:2: panic
run: interface conversion: interface {} is struct {}, not interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0x140002c8a00, 0x40)
	/Users/marc/sdk/go1.16.2/src/runtime/debug/stack.go:24 +0x88
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0x140001cdc40)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:491 +0x94
panic(0x102c0d2a0, 0x1400042abd0)
	/Users/marc/sdk/go1.16.2/src/runtime/panic.go:965 +0x14c
github.com/traefik/yaegi/interp.runCfg.func1(0x1400034a0b0, 0x14000452c00, 0x140001cda10)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:185 +0x1e8
panic(0x102c0d2a0, 0x1400042abd0)
	/Users/marc/sdk/go1.16.2/src/runtime/panic.go:965 +0x14c
github.com/traefik/yaegi/interp.getMethodByName.func1(0x1400034a0b0, 0x14000042a00)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:1843 +0x51c
github.com/traefik/yaegi/interp.runCfg(0x14000452c00, 0x1400034a0b0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:191 +0x8c
github.com/traefik/yaegi/interp.(*Interpreter).run(0x14000348000, 0x14000452100, 0x1400034a000)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:122 +0x244
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x14000348000, 0x140002a6f00, 0x9d, 0x16dc5f8e8, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:583 +0x5e8
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0x14000348000, 0x16dc5f8e8, 0x16, 0x140002a6e00, 0x9d, 0x0, 0x0, 0x1029c9d30)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:405 +0xc4
main.runFile(0x14000348000, 0x16dc5f8e8, 0x16, 0x1, 0x1)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:123 +0x84
main.run(0x14000140010, 0x1, 0x1, 0x14000102480, 0x1400006fea8)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:89 +0x724
main.main()
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x324
```

### LINKED ISSUE #1071: Call flow graph generation panics on var declaration when wrapped as main
The following code triggers a panic in `(*Interpreter).cfg` when called by `(*Interpreter).Eval`:

```go
i := ""
var j int
```

```
$ yaegi
> i := ""; var j int
1:41: CFG post-order panic: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
runtime/debug.Stack(0x1, 0xc000200a00, 0x40)
        /goroot/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc00020ff78)
        /workdir/yaegi/interp/interp.go:491 +0xc5
panic(0x1ab7500, 0xc0001a1da0)
        /goroot/src/runtime/panic.go:969 +0x175
github.com/traefik/yaegi/interp.(*Interpreter).cfg.func2.1(0xc0001c7200)
        /workdir/yaegi/interp/cfg.go:468 +0xb3
panic(0x1a1fd60, 0x214bd30)
        /goroot/src/runtime/panic.go:969 +0x175
github.com/traefik/yaegi/interp.(*Interpreter).cfg.func2(0xc0001c7200)
        /workdir/yaegi/interp/cfg.go:1903 +0x1963
github.com/traefik/yaegi/interp.(*node).Walk(0xc0001c7200, 0xc00020fdf8, 0xc00020fdc8)
        /workdir/yaegi/interp/interp.go:231 +0xa5
github.com/traefik/yaegi/interp.(*node).Walk(0xc0001c7100, 0xc00020fdf8, 0xc00020fdc8)
        /workdir/yaegi/interp/interp.go:228 +0x66
github.com/traefik/yaegi/interp.(*node).Walk(0xc0001c7000, 0xc00020fdf8, 0xc00020fdc8)
        /workdir/yaegi/interp/interp.go:228 +0x66
github.com/traefik/yaegi/interp.(*node).Walk(0xc0001c6c00, 0xc00020fdf8, 0xc00020fdc8)
        /workdir/yaegi/interp/interp.go:228 +0x66
github.com/traefik/yaegi/interp.(*Interpreter).cfg(0xc000372000, 0xc0001c6c00, 0xc00036e820, 0x4, 0xc00036e820, 0x4, 0x0, 0x0, 0xc0001c6c00)
        /workdir/yaegi/interp/cfg.go:63 +0x20f
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc000372000, 0xc0001c2780, 0x13, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
        /workdir/yaegi/interp/interp.go:518 +0x2f3
github.com/traefik/yaegi/interp.(*Interpreter).Eval(...)
        /workdir/yaegi/interp/interp.go:389
github.com/traefik/yaegi/interp.(*Interpreter).EvalWithContext.func1(0xc000181aa0, 0xc000372000, 0xc0001c2780, 0x13, 0xc0001a1b40, 0xc000230750)
        /workdir/yaegi/interp/interp.go:612 +0x85
created by github.com/traefik/yaegi/interp.(*Interpreter).EvalWithContext
        /workdir/yaegi/interp/interp.go:610 +0x150
```

### PR DESCRIPTION
**Pull request by mvertes**
Avoid to test directly for a type category, as it may give wrong
results for aliased types, where the interesting category remains
masked.  Instead, use some property helpers, such as isFuncSrc,
isPtrSrc and isInterfaceSrc to check if a type is of source function,
source pointer or source interface respectively (versus runtime
defined function, pointer or interface).

Fixes #1068.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -1148,7 +1136,7 @@ func call(n *node) {
 			j := n.findex + i
 			ret := n.child[0].typ.ret[i]
 			callret := n.anc.val.(*node).typ.ret[i]
-			if callret.cat == interfaceT && len(callret.field) > 0 && ret.cat != interfaceT {
+			if isInterfaceSrc(callret) && !isEmptyInterface(callret) {
```
Comment (mpl) [inline interp/run.go:1139]: Are you sure about this one? it looks like the part "ret.cat != interfaceT" disappeared.

**Review by mpl — CHANGES_REQUESTED** [review]

File: interp/run.go [hunk 2]
```diff
@@ -1106,13 +1104,8 @@ func call(n *node) {
...
 			switch {
-			case arg.cat == interfaceT:
-				if len(arg.field) > 0 {
-					values = append(values, genValueInterface(c))
-					break
-				}
-				// empty interface, do not wrap it.
-				values = append(values, genValue(c))
+			case isInterfaceSrc(arg) && !isEmptyInterface(arg):
+				values = append(values, genValueInterface(c))
```
[the remark this answers is not in the document]
Comment (mvertes) [reply interp/run.go]: Done as suggested.

File: interp/run.go (hunk 1 above)
Comment (mvertes) [reply interp/run.go]: I added the missing test.

**Review by mpl — APPROVED** [review]
