### PR TITLE
interp: fix testing for nil interface values

### LINKED ISSUE #924: testing nil interface
The following program `sample.go` triggers a panic:

```go
package main

type I interface {
    Hello()
}

type T struct {
    h I
}

func (t *T) Hello() { println("Hello") }

func main() {
    t := &T{}
    println(t.h != nil)
}
```

Expected result:
```console
$ go run ./sample.go
false
```

Got:
```console
$ yaegi ./sample.go
/home/marc/yt/nil-interf.go:14:8: panic
run: interface conversion: interface {} is nil, not interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0002e0600, 0x40)
        /usr/lib/go/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc0001e3c70)
        /home/marc/go/src/github.com/traefik/yaegi/interp/interp.go:480 +0xc5
panic(0xe1e960, 0xc000446cf0)
        /usr/lib/go/src/runtime/panic.go:969 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0003640a0, 0xc00046ca00)
        /home/marc/go/src/github.com/traefik/yaegi/interp/run.go:124 +0x217
panic(0xe1e960, 0xc000446cf0)
        /usr/lib/go/src/runtime/panic.go:969 +0x1b9
github.com/traefik/yaegi/interp.isNotNil.func3(0xc0003640a0, 0xc000205400)
        /home/marc/go/src/github.com/traefik/yaegi/interp/run.go:3161 +0x134
github.com/traefik/yaegi/interp.runCfg(0xc00046ca00, 0xc0003640a0)
        /home/marc/go/src/github.com/traefik/yaegi/interp/run.go:130 +0x6e
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc00035e000, 0xc00046c100, 0xc000364000)
        /home/marc/go/src/github.com/traefik/yaegi/interp/run.go:108 +0x2af
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc00035e000, 0xc0004640f0, 0xf0, 0x7ffd3c72b4d8, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/marc/go/src/github.com/traefik/yaegi/interp/interp.go:572 +0x809
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc00035e000, 0x7ffd3c72b4d8, 0x1b, 0xc000464000, 0xf0, 0x0, 0x0, 0xc000212b60)
        /home/marc/go/src/github.com/traefik/yaegi/interp/interp.go:394 +0xfa
main.runFile(0xc00035e000, 0x7ffd3c72b4d8, 0x1b, 0xc0002001e0, 0x1)
        /home/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:123 +0xae
main.run(0xc000128030, 0x1, 0x1, 0x13, 0x13)
        /home/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:89 +0x7e5
main.main()
        /home/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x415
```

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #924.

### CODE REVIEW

File: _test/nil4.go [hunk 1]
```diff
@@ -0,0 +1,24 @@
+package main
```
Comment (mpl) [inline _test/nil4.go:1]: As _test/nil3.go and _test/nil4.go have exactly the same setup (only the main(), and the Output change), they could be merged together, right?

File: interp/run.go [hunk 2]
```diff
@@ -3087,9 +3087,9 @@ func isNil(n *node) {
 		fnext := getExec(n.fnext)
 		if c0.typ.cat == interfaceT {
 			n.exec = func(f *frame) bltn {
-				vi := value(f).Interface().(valueInterface)
-				if (vi == valueInterface{} ||
-					vi.node.kind == basicLit && vi.node.typ.cat == nilT) {
+				v := value(f)
+				vi, ok := v.Interface().(valueInterface)
+				if ok && (vi == valueInterface{} || vi.node.kind == basicLit && vi.node.typ.cat == nilT) || v.IsNil() {
```
Comment (mpl) [inline interp/run.go:3092]: Possible optimization: if we start by testing v.IsNil(), then we don't even need to systematically do the type assertion, i.e.:

```
if v.IsNil() {
    // blabla
    // return tnext
}
vi, ok := v.Interface().(valueInterface)
if ok && (vi == valueInterface{} || vi.node.kind == basicLit && vi.node.typ.cat == nilT) {
...
```

However what I'm proposing is not exactly equivalent because in the current version we _only_ do v.isNil() if the type assertion is not ok, and maybe that order is important. So I'm not sure.

File: interp/run.go [hunk 3]
```diff
@@ -3109,7 +3109,12 @@ func isNil(n *node) {
 	} else {
 		if c0.typ.cat == interfaceT {
 			n.exec = func(f *frame) bltn {
-				dest(f).SetBool(value(f).Interface().(valueInterface) == valueInterface{})
+				v := value(f)
+				if vi, ok := v.Interface().(valueInterface); ok {
```
Comment (mpl) [inline interp/run.go:3113]: Same remark as above.

File: interp/run.go (hunk 2 above)
Comment (mvertes) [reply interp/run.go:3092]: Your suggestion is causing regressions (which I haven't investigated). Better to keep the code as is.

File: interp/run.go (hunk 3 above)
Comment (mvertes) [reply interp/run.go:3113]: idem as above

File: interp/run.go (hunk 2 above)
Comment (mpl) [reply interp/run.go:3092]: ok, interesting.

**Review by mpl — APPROVED** [review]
