### PR TITLE
interp: handle struct with multiple recursive fields

### LINKED ISSUE #1371: struct with multiple recursive fields
### The following program `sample.go` triggers an unexpected result

```go
package main

import "fmt"

type node struct {
    parent *node
    child  []*node
    key    string
}

func main() {
    root := &node{key: "root"}
    root.child = nil
    fmt.Println("root:", root)
}
```

### Expected result

```console
$ go run ./sample.go
root: &{<nil> [] root}
```

### Got

```console
$ yaegi ./sample.go
./sample.go:13:16: panic
run: reflect.Set: value of type []*unsafe2.dummy is not assignable to type []*struct { Xparent *unsafe2.dummy; Xchild []*unsafe2.dummy; Xkey string }
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/marc/sdk/go1.17.8/src/runtime/debug/stack.go:24 +0x88
github.com/traefik/yaegi/interp.(*Interpreter).Execute.func1(0x140004c7ae0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/program.go:131 +0x8c
panic({0x103902d60, 0x14000118c50})
	/Users/marc/sdk/go1.17.8/src/runtime/panic.go:1038 +0x21c
github.com/traefik/yaegi/interp.runCfg.func1(0x14000366210, 0x140004bec60, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:194 +0x164
panic({0x103902d60, 0x14000118c50})
	/Users/marc/sdk/go1.17.8/src/runtime/panic.go:1038 +0x21c
reflect.Value.assignTo({0x14000110a80, 0x14000122810, 0x197}, {0x10371c8a9, 0xb}, 0x14000110b40, 0x0)
	/Users/marc/sdk/go1.17.8/src/reflect/value.go:2810 +0x2cc
reflect.Value.Set({0x14000110b40, 0x140004ca818, 0x197}, {0x14000110a80, 0x14000122810, 0x197})
	/Users/marc/sdk/go1.17.8/src/reflect/value.go:1918 +0xa4
github.com/traefik/yaegi/interp.assign.func4(0x14000366210)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:701 +0x154
github.com/traefik/yaegi/interp.runCfg(0x140004bec60, 0x14000366210, 0x140004be000, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:202 +0x268
github.com/traefik/yaegi/interp.(*Interpreter).run(0x14000364000, 0x140004be000, 0x14000366000)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:121 +0x3d4
github.com/traefik/yaegi/interp.(*Interpreter).Execute(0x14000364000, 0x140004ca360)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/program.go:157 +0x1e0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x14000364000, {0x140002e0410, 0xc6}, {0x16cf7b750, 0x15}, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:615 +0x98
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0x14000364000, {0x16cf7b750, 0x15})
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:508 +0xe8
main.runFile(0x14000364000, {0x16cf7b750, 0x15}, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:153 +0xb0
main.run({0x14000032050, 0x1, 0x1})
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:116 +0xe14
main.main()
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x384
```

### Yaegi Version

0.11.2

### Additional Notes

This issue was found when using `github.com/spyzhov/ajson`

### PR DESCRIPTION
**Pull request by mvertes**
In case of a recursive struct with several recursive fields of
different types, only the first one was properly fixed when
constructing the corresponding reflect type. We now memorize and
process all fields at the same depth level.

Fixes #1371.

### CODE REVIEW

File: interp/type.go [hunk 1]
```diff
@@ -1827,28 +1827,29 @@ func (t *itype) refType(ctx *refTypeContext) reflect.Type {
...
+						if name == s.path+"/"+s.name {
+							fieldFix = append(fieldFix, i)
+						}
 					}
 				}
 			}
 		}
 
 		// The rtype has now been built, we can go back and rebuild
 		// all the recursive types that relied on this type.
```
Comment (mpl) [inline interp/type.go:1847]:
```suggestion
		// all the recursive types that relied on this type.
		// However, as we are keyed by type name, if two or more (recursive) fields at
		// the same depth level are of the same type, or a "variation" of the same type
		// (slice of, map of, etc), they "mask" each other, and only one
		// of them is in ctx.refs. That is why the code around here is a bit convoluted,
		// and we need both the loop above, around all the struct fields, and the loop
		// below, around the ctx.refs.		
```

**Review by mpl — APPROVED** [review]
