### PR TITLE
interp: fix handling map of interfaces

### LINKED ISSUE #1189: Crash when calling the method of an object in the map
### The following program `sample.go` triggers an unexpected result

```go
package main

import "fmt"

type I interface {
	Foo() int
}

type S1 struct {
	i int
}

func (s S1) Foo() int { return s.i }

type S2 struct{}

func (s *S2) Foo() int { return 42 }

func main() {
	var Is = map[string]I{
		"foo": S1{21},
		"bar": &S2{},
	}

	for _, s := range Is {
		fmt.Println(s.Foo())
	}
	fmt.Println(Is["foo"].Foo())
}
```

### Expected result

```console
21
42
21
```

### Got

```console
main.go:25:2: panic
run: reflect: call of reflect.Value.Elem on struct Value
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0002eea00, 0x40)
	/usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc0001c7c18)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/interp.go:504 +0xc8
panic(0x1a43ae0, 0xc00000e8a0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc00036c160, 0xc00048ee00, 0xc0001c79f8)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/run.go:185 +0x253
panic(0x1a43ae0, 0xc00000e8a0)
	/usr/local/opt/go/libexec/src/runtime/panic.go:965 +0x1b9
reflect.Value.Elem(0x1a908e0, 0xc000032f80, 0x99, 0x99, 0xc000089350, 0x98)
	/usr/local/opt/go/libexec/src/reflect/value.go:843 +0x1a5
github.com/traefik/yaegi/interp.rangeMap.func1(0xc00036c160, 0xc00009cf00)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/run.go:2736 +0x18d
github.com/traefik/yaegi/interp.runCfg(0xc00048ee00, 0xc00036c160)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/run.go:191 +0x87
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc00000c1e0, 0xc00048de00, 0xc00036c000)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/run.go:122 +0x2b0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc00000c1e0, 0xc0002e8480, 0x175, 0x7ffeefbff306, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/interp.go:596 +0x80c
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc00000c1e0, 0x7ffeefbff306, 0x7, 0xc0002e8300, 0x175, 0x0, 0x0, 0xc0001c7cb0)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/interp/interp.go:418 +0x105
main.runFile(0xc00000c1e0, 0x7ffeefbff306, 0x7, 0x0, 0x1, 0x0)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/cmd/yaegi/run.go:149 +0xb1
main.run(0xc000134010, 0x1, 0x1, 0xc00010c101, 0xc000102480)
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/cmd/yaegi/run.go:112 +0x9c5
main.main()
	/go/pkg/mod/github.com/traefik/yaegi@v0.9.20/cmd/yaegi/yaegi.go:144 +0x415
```

### Yaegi Version

v0.9.20

### Additional Notes

This issue is introduced **after** `v0.9.14`

_No response_

### PR DESCRIPTION
**Pull request by mvertes**
Map handling builtins getIndexMap and rangeMap had some leftover
code of previous way of emulating interfaces, which was modified
following changes in #1017.

Specific code for interfaceT is removed, as not necessary anymore.
Map builtins are now simplified and more robust.

Fixes #1189.

### CODE REVIEW

File: _test/issue-1189.go [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+func main() {
+	Is := map[string]I{
+		"foo": S1{21},
+		"bar": &S2{},
+	}
+	n := 0
+	for _, s := range Is {
+		n += s.Foo()
+	}
+	println(n, Is["foo"].Foo())
```
Comment (mpl) [inline _test/issue-1189.go:26]: With this suggestion we also test that the part that was removed L1670 is ok, and not just the part that was removed L1625.
```suggestion
	bar := "bar"
	println(n, Is["foo"].Foo(), Is[bar].Foo())
```

File: _test/issue-1189.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+}
+
+// Output:
+// 63 21
```
Comment (mpl) [inline _test/issue-1189.go:30]:
```suggestion
// 63 21 42
```

File: _test/issue-1189.go (hunk 1 above)
Comment (mvertes) [reply _test/issue-1189.go]: applied

File: _test/issue-1189.go (hunk 2 above)
Comment (mvertes) [reply _test/issue-1189.go]: applied

**Review by mpl — APPROVED** [review]
