### PR TITLE
fix: allow yaegi command to interpret itself

### LINKED ISSUE #890: yaegi interpreting itself
The following program `sample.go` triggers a panic:

```console
$ yaegi  -syscall -unsafe -unrestricted github.com/traefik/yaegi/cmd/yaegi -e "println(1)"
```

Expected result:
```console
1
```

Got:
```console
cmd/yaegi/run.go:122:19: package interp "github.com/traefik/yaegi/interp" has no symbol Panic
run: cmd/yaegi/run.go:122:19: package interp "github.com/traefik/yaegi/interp" has no symbol Panic
```

### PR DESCRIPTION
**Pull request by mvertes**
Since the introduction of restricted stdlib and syscall symbols, the
capability of yaegi to interpret itself was broken.
The use of unrestricted symbols is now also controlled by environment
variables, to allow propagation accross nested interpreters.
The interpreter Panic symbol was not wrapped, this is fixed now.
the import path resolution was failing if the working directory was
outside of GOPATH.
The documentation and readme have been ajusted.

Fixes #890.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -2034,7 +2034,7 @@ func doCompositeBinStruct(n *node, hasType bool) {
 			}
 		} else {
 			fieldIndex[i] = []int{i}
-			if c.typ.cat == funcT {
+			if c.typ.cat == funcT && len(c.child) > 1 {
```
Comment (mpl) [inline interp/run.go:2037]: I do not understand this change.
I understand we are in the case of a literal composite, and one of its fields is defined without a key, just the value. and the value is a function. Could you give me an example of a case where
 `c.typ.cat == funcT && len(c.child) == 1`
and one where
 `c.typ.cat == funcT && len(c.child) == 2`
so i can understand the difference?

**Review by mpl — CHANGES_REQUESTED** [review]

File: cmd/yaegi/run.go [hunk 2]
```diff
@@ -46,13 +49,22 @@ func run(arg []string) error {
 	i.Use(interp.Symbols)
 	if useSyscall {
 		i.Use(syscall.Symbols)
+		if err := os.Setenv("YAEGI_SYSCALL", "1"); err != nil {
+			return err
+		}
```
[the remark this answers is not in the document]
Comment (mvertes) [reply cmd/yaegi/run.go:54]: That's right. Will add a comment about that.

File: interp/run.go (hunk 1 above)
Comment (mvertes) [reply interp/run.go:2037]: This may happen when initializing a runtime defined struct with a function field (`typ.Field(i).Type == reflect.Func`) with an interpreter defined stuct with a function field already being a reflect.Value from runtime.

I met this case when interpreting (inception mode) `cmd/yaegi/test.go` at line 123:
```go
benchmarks = append(benchmarks, testing.InternalBenchmark{name, fun})
```
where `fun` is provided through a type switch assign, thus already converted to the runtime type.

Comment (mpl) [reply interp/run.go:2037]: something's still unclear to me, but I'll clarify with you later. No need to block the PR for that.

**Review by mpl — APPROVED** [review]
