### PR TITLE
interp: improve handling of interface values

### LINKED ISSUE #1156: panic when reassigning (native) interface value
Equivalent to #1138 , and _test/issue-1136.go (which probably should have been named issue-1138.go btw), but with native interfaces instead of runtime ones:

The following program `sample.go` triggers a panic:

```go
package main

import (
	"fmt"
)

type myInterface interface {
	myFunc() string
}

type V struct{}

func (v *V) myFunc() string { return "hello" }

type U struct {
	v myInterface
}

func (u *U) myFunc() string { return u.v.myFunc() }

func main() {
	x := V{}
	y := myInterface(&x)
	y = &U{y}
	fmt.Println(y.myFunc())
}

// Output:
// hello
```

Expected result:
```console
$ go run ./sample.go
hello
```

Got:
```console
$ yaegi ./sample.go
./sample.go:19:38: panic
./sample.go:25:14: panic
run: runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc0002eca00, 0x40)
	/Users/mpl/go1/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc0001afc18)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:503 +0xc8
panic(0x1a547c0, 0x217db50)
	/Users/mpl/go1/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0000ceb00, 0xc000482d00, 0xc0001af9f8)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:185 +0x253
panic(0x1a547c0, 0x217db50)
	/Users/mpl/go1/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc0000cec60, 0xc000482100, 0xc0001af7e8)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:185 +0x253
panic(0x1a547c0, 0x217db50)
	/Users/mpl/go1/src/runtime/panic.go:965 +0x1b9
github.com/traefik/yaegi/interp.getMethodByName.func1(0xc0000cec60, 0xc0002e0b80)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:1824 +0x1ed
github.com/traefik/yaegi/interp.runCfg(0xc000482100, 0xc0000cec60)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:191 +0x87
github.com/traefik/yaegi/interp.call.func7(0xc0000ceb00, 0xc0001c5ea0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:1272 +0xd05
github.com/traefik/yaegi/interp.runCfg(0xc000482d00, 0xc0000ceb00)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:191 +0x87
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc00000c1e0, 0xc000482500, 0xc0000ce9a0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/run.go:122 +0x2b0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc00000c1e0, 0xc0000b0c60, 0x153, 0x7ffeefbff672, 0x15, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:595 +0x80c
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc00000c1e0, 0x7ffeefbff672, 0x15, 0xc0000b0b00, 0x153, 0x0, 0x0, 0xc0001afcb0)
	/Users/mpl/src/github.com/traefik/yaegi/interp/interp.go:417 +0x105
main.runFile(0xc00000c1e0, 0x7ffeefbff672, 0x15, 0x0, 0x1, 0x0)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:139 +0xb1
main.run(0xc0000321d0, 0x1, 0x1, 0xc00000a501, 0xc000001680)
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/run.go:102 +0x99d
main.main()
	/Users/mpl/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:133 +0x479
```

### PR DESCRIPTION
**Pull request by mvertes**
In selector resolution, struct field matching now precedes
method matching. Before struct field matching could be skipped
in case of a matching method, which is incorrect, as demontrated
by _test/issue-1156.go.

Field lookup has been fixed to operate on recursive structures.

Concrete type values are derived when filling a receiver for
interface methods.

LookupBinField has been fixed to skip non struct values.

LookupMethod has been fixed to iterate on interface values as
well as concrete type values.

Fixes #1156.

### CODE REVIEW

File: interp/type.go [hunk 1]
```diff
@@ -1282,10 +1294,13 @@ func (t *itype) lookupBinField(name string) (s reflect.StructField, index []int,
...
 		return
 	}
-	rt := t.rtype
+	rt := t.TypeOf()
 	if t.cat == valueT && rt.Kind() == reflect.Ptr {
 		rt = rt.Elem()
 	}
+	if rt.Kind() != reflect.Struct {
+		return
+	}
```
Comment (mpl) [inline interp/type.go:1303]: But if we have a pointer of a pointer, then `rt.Elem()` L1299 will return a reflect.Ptr, and the check L1301 will fail, no? Don't we want some kind of recursion here?
Or maybe I'm confused and this can never happen thanks to L1291..., I'm not sure.
Feel free to disregard that comment if it does not make any sense.

File: interp/type.go [hunk 2]
```diff
@@ -1350,7 +1365,7 @@ func (t *itype) lookupMethod(name string) (*node, []int) {
 				}
 			}
 		}
-		if t.cat == aliasT {
+		if t.cat == aliasT || isInterfaceSrc(t) && t.val != nil {
```
Comment (mpl) [inline interp/type.go:1368]: Did you notice that in `lookupFieldOrMethod` (which calls `lookupMethod`), we already deal with the case of `t.cat == interfaceT`? So I think there's probably some more refactoring we could related to these calls. But I understand if you want to do it later.

File: interp/type.go (hunk 1 above)
Comment (mvertes) [reply interp/type.go:1303]: ok

File: interp/cfg.go [hunk 3]
```diff
@@ -1572,66 +1508,138 @@ func (interp *Interpreter) cfg(root *node, importPath string) ([]*node, error) {
...
+						n.gen = getIndexSeq
+						n.typ = n.typ.fieldSeq(ti)
+						if n.typ.cat == funcT {
+							// Function in a struct field is always wrapped in reflect.Value.
+							rtype := n.typ.TypeOf()
+							n.typ = &itype{cat: valueT, rtype: rtype, val: n.typ}
+						}
+					}
+					break
+				} else if s, lind, ok := n.typ.lookupBinField(n.child[1].ident); ok {
```
[the remark this answers is not in the document]
Comment (mvertes) [reply interp/cfg.go:1538]: ok

File: interp/type.go (hunk 2 above)
Comment (mvertes) [reply interp/type.go:1368]: Yes I noticed, and indeed intend a refactoring to be done after this PR

**Review by mpl — APPROVED** [review]
