### PR TITLE
interp: improve the behaviour of interface{} function parameters

### LINKED ISSUE #435: Interface defined in interpreter not picked up by fmt.Println
The following program `sample.go` has wrong output:

```go
package main

import (
	"fmt"
)

type Foo int

func (Foo) String() string {
	return "foo"
}

func print(arg interface{}) {
	fmt.Println(arg)
}

func main() {
	var arg Foo
	var f = print
	f(arg)
}
```

Expected result:
```console
$ go run ./sample.go
foo
```

Got:
```console
$ yaegi ./sample.go
0
```

It appears that `fmt.Println` does not see that `Foo` declared in the interpreter implements `fmt.Stringer` and simply outputs the int value.

I met the same problem with my interpreter gomacro and I have no idea how to fix this - except by "cheating" (i.e. replacing `fmt.Println` with an interpreter-aware implementation)

### PR DESCRIPTION
**Pull request by mvertes**
We finally address a long standing limitation of the interpreter:
the capacity to generate the correct interface wrapper for an
anonymous interface{} function parameter of a binary function.

It allows for example fmt.Printf to invoke the String method
of an object defined within the interpreter, or json.Marshal
to invoke a textMarshaler method if it exists and if there is
no Marshaler method already defined for the passed interpreter
object.

To achieve that, we add a new mapType part of the "Used" symbols
to describe what not empty interfaces are expected and in which
priority order. This information can not be guessed and is found
in the related package documentation, then captured in stdlib/maptypes.go.

Then, at compile time and/or during execution, a lookup on mapTypes
is performed to allow the correct wrapper to be generated.

This change adds a new MapType type to the stdlib package.

Fixes #435.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -1527,6 +1534,19 @@ func callBin(n *node) {
 				break
 			}
 
+			// defType is the target type for an eventual interface wrapper.
+			var defType reflect.Type
+			if variadic >= 0 && i+rcvrOffset >= variadic {
+				defType = funcType.In(variadic)
+			} else {
+				defType = funcType.In(rcvrOffset + i)
+			}
```
Comment (mpl) [inline interp/run.go:1543]: as an optimization, this could be in an else after the if of 1544.

**Review by mpl — APPROVED** [review]

File: interp/run.go (hunk 1 above)
Comment (mvertes) [reply interp/run.go:1543]: I tested this change and tests fails at _test/issue-1166.go because `defType` is now nil when entering the switch at run.go:1551 (was not before).

Comment (mpl) [reply interp/run.go:1543]: One way that works is:
```
			// defType is the target type for a potential interface wrapper.
			var defType reflect.Type
			if getMapType != nil {
				if rt := getMapType(c.typ); rt != nil {
					defType = rt
				}
			}
			if defType == nil {
				if variadic >= 0 && i+rcvrOffset >= variadic {
					defType = funcType.In(variadic)
				} else {
					defType = funcType.In(rcvrOffset + i)
				}
			}
```

I haven't found an elegant way to invert the first condition yet though (in order to remove the `if defType == nil {`).

File: stdlib/maptypes.go [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+	"fmt"
+	"log"
+	"reflect"
+)
+
+func init() {
+	mt := []reflect.Type{
+		reflect.TypeOf((*fmt.Formatter)(nil)).Elem(),
+		reflect.TypeOf((*fmt.Stringer)(nil)).Elem(),
+	}
```
Comment (cosmos72) [inline stdlib/maptypes.go:16]: What about adding also `fmt.GoStringer` ?

See https://pkg.go.dev/fmt#GoStringer

Comment (mvertes) [reply stdlib/maptypes.go:16]: In fact, the solution here is incomplete for `Printf`, as the non empty interface to target also depends in this case from the the format verbs, as `%#v` which requires a `GoStringer` instead of a `Stringer` for `%v`. For now we ignore this, and thus not adding `GoStringer`.

Having a full solution here for `Printf` would probably require to rewrite it inside the interpreter to parse the verbs in format string. It's too much of an edge case for us, and the current solution seems a better compromise.
