### PR TITLE
interp: fix sending object implementing an interface through channel

### LINKED ISSUE #1010: Cannot send a concrete type to a chan of an interface
The following program `sample.go` triggers a panic:

```go
package main

import (
    "encoding/json"
    "fmt"
)

type MyJsonMarshaller struct {
}

func (m MyJsonMarshaller) MarshalJSON() ([]byte, error) {
    return []byte("{}"), nil
}

func main() {
    ch := make(chan json.Marshaler, 1)

    marshaller := MyJsonMarshaller{}
    ch <- marshaller
    fmt.Println("OK")
}
```

Expected result:
```console
$ go run ./sample.go
// output
OK
```

Got:
```console
$ yaegi ./sample.go
// output
./main.go:20:5: panic
run: reflect.Value.Send: value of type struct {} is not assignable to type json.Marshaler
goroutine 1 [running]:
runtime/debug.Stack(0x1, 0xc000166a00, 0x40)
	/home/juliens/go-current/src/runtime/debug/stack.go:24 +0x9f
github.com/traefik/yaegi/interp.(*Interpreter).eval.func1(0xc000225c70)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/interp.go:485 +0xc5
panic(0xdc9fa0, 0xc000195050)
	/home/juliens/go-current/src/runtime/panic.go:969 +0x1b9
github.com/traefik/yaegi/interp.runCfg.func1(0xc000132dc0, 0xc0004d4e00, 0xc000225a60)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/run.go:184 +0x247
panic(0xdc9fa0, 0xc000195050)
	/home/juliens/go-current/src/runtime/panic.go:969 +0x1b9
reflect.Value.assignTo(0xdf55e0, 0x1571db8, 0x199, 0xf0fea4, 0x12, 0xe1e2a0, 0x0, 0x0, 0x0, 0x0)
	/home/juliens/go-current/src/reflect/value.go:2425 +0x405
reflect.Value.send(0xc0001b0a80, 0xc00000e840, 0x192, 0xdf55e0, 0x1571db8, 0x199, 0x0, 0x0)
	/home/juliens/go-current/src/reflect/value.go:1534 +0xa6
reflect.Value.Send(0xc0001b0a80, 0xc00000e840, 0x192, 0xdf55e0, 0x1571db8, 0x199)
	/home/juliens/go-current/src/reflect/value.go:1523 +0x93
github.com/traefik/yaegi/interp.send.func2(0xc000132dc0, 0xc0004d2340)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/run.go:3162 +0xb6
github.com/traefik/yaegi/interp.runCfg(0xc0004d4e00, 0xc000132dc0)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/run.go:190 +0x87
github.com/traefik/yaegi/interp.(*Interpreter).run(0xc0003d0000, 0xc0004d4600, 0xc000132b00)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/run.go:121 +0x2b0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0xc0003d0000, 0xc00034c480, 0x165, 0x7fff6c6b62cd, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/interp.go:577 +0x809
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0xc0003d0000, 0x7fff6c6b62cd, 0x9, 0xc00034c300, 0x165, 0x0, 0x0, 0xc000171d40)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/interp/interp.go:399 +0xfa
main.runFile(0xc0003d0000, 0x7fff6c6b62cd, 0x9, 0xc00007cd20, 0x1)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:123 +0xae
main.run(0xc00000c090, 0x1, 0x1, 0x13, 0x13)
	/home/juliens/dev/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:89 +0x7e5
main.main()
	/home/juliens/dev/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x415

```

Just for information if I use this code, it works as expected.
```go
package main

import (
    "encoding/json"
    "fmt"
)

type MyJsonMarshaller struct {
}

func (m MyJsonMarshaller) MarshalJSON() ([]byte, error) {
    return []byte("{}"), nil
}

func main() {
    ch := make(chan json.Marshaler, 1)

    marshaller := MyJsonMarshaller{}
    var b json.Marshaler = marshaller
    ch <- b
    fmt.Println("OK")
}
```

### PR DESCRIPTION
**Pull request by mvertes**
A channel can be used to interchange data with the pre-compiled
runtime and therefore objects impletementing interfaces must be
wrapped if necessary, using genInterfaceWrapper.

A similar treatment could be applied when sending interpreted
functions over a channel, to be provided in a new PR.

Fixes #1010.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -3133,19 +3133,27 @@ func convertConstantValue(n *node) {
...
+	switch {
+	case isInterfaceBin(c0.typ.val):
+		value1 = genInterfaceWrapper(c1, c0.typ.val.rtype)
+	default:
+		value1 = genValue(c1)
+	}
 
 	if n.interp.cancelChan {
-		// Cancellable send
+		// Send is cancelable, may have some overhead.
```
Comment (mpl) [inline interp/run.go:3149]:
```suggestion
		// Send is cancellable, may have some overhead.
```

File: interp/run.go [hunk 2]
```diff
@@ -3133,19 +3133,27 @@ func convertConstantValue(n *node) {
...
+
+	var value1 func(*frame) reflect.Value // Value to send.
+	switch {
+	case isInterfaceBin(c0.typ.val):
+		value1 = genInterfaceWrapper(c1, c0.typ.val.rtype)
+	default:
+		value1 = genValue(c1)
+	}
 
 	if n.interp.cancelChan {
```
Comment (mpl) [inline interp/run.go:3148]: we could 1) invert that test, and 2) return early, for the least amount of indented code.

File: interp/run.go (hunk 1 above)
Comment (mvertes) [reply interp/run.go:3149]: the correct spelling here is *cancel-able*, according to `aspell`, which makes *cancelable* ok and *cancellable* not ok.

**Review by mpl — APPROVED** [review]
