### PR TITLE
interp: fix setting of interface value from nested function calls

### LINKED ISSUE #1320: setting interface from nested func call
### The following program `sample.go` triggers an unexpected result

```go
package main
                                                                                
type Pooler interface {                                                         
    Get() string                                                                
}                                                                               
                                                                                
type baseClient struct {                                                        
    connPool Pooler                                                             
}                                                                               
                                                                                
type connPool struct {                                                          
    name string                                                                 
}                                                                               
                                                                                
func (c *connPool) Get() string { return c.name }                               
                                                                                
func newBaseClient(p Pooler) *baseClient {                                      
    return &baseClient{connPool: p}                                             
}                                                                               
                                                                                
func newConnPool() *connPool { return &connPool{name: "connPool"} }             

func main() {                                                                   
    b := newBaseClient(newConnPool())                                           
    println(b.connPool.(*connPool).name)                                        
}
```

### Expected result

```console
$ go run ./sample.go
connPool
```

### Got

```console
$ yaegi ./sample.go
/Users/marc/yt/call1.go:24:21: panic
run: reflect.Set: value of type *struct { Xname string } is not assignable to type interp.valueInterface
goroutine 1 [running]:
runtime/debug.Stack()
	/Users/marc/sdk/go1.17.3/src/runtime/debug/stack.go:24 +0x88
github.com/traefik/yaegi/interp.(*Interpreter).Execute.func1(0x140001bbae0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/program.go:131 +0x8c
panic({0x104f8ecc0, 0x140001a38c0})
	/Users/marc/sdk/go1.17.3/src/runtime/panic.go:1038 +0x21c
github.com/traefik/yaegi/interp.runCfg.func1(0x140000d0bb0, 0x140004bec60, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:193 +0x164
panic({0x104f8ecc0, 0x140001a38c0})
	/Users/marc/sdk/go1.17.3/src/runtime/panic.go:1038 +0x21c
reflect.Value.assignTo({0x140001ceb40, 0x14000010b50, 0x196}, {0x104da9463, 0xb}, 0x1050075e0, 0x0)
	/Users/marc/sdk/go1.17.3/src/reflect/value.go:2797 +0x2cc
reflect.Value.Set({0x1050075e0, 0x14000033460, 0x199}, {0x140001ceb40, 0x14000010b50, 0x196})
	/Users/marc/sdk/go1.17.3/src/reflect/value.go:1905 +0xa4
github.com/traefik/yaegi/interp.call.func7(0x140000d0bb0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:1364 +0xb4c
github.com/traefik/yaegi/interp.runCfg(0x140004bec60, 0x140000d0bb0, 0x140004be120, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:201 +0x268
github.com/traefik/yaegi/interp.(*Interpreter).run(0x140000f9b00, 0x140004be120, 0x140000d0a50)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/run.go:120 +0x3d4
github.com/traefik/yaegi/interp.(*Interpreter).Execute(0x140000f9b00, 0x140004c5710)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/program.go:157 +0x1e0
github.com/traefik/yaegi/interp.(*Interpreter).eval(0x140000f9b00, {0x140002ea780, 0x1c3}, {0x16b8eb728, 0x17}, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:615 +0x98
github.com/traefik/yaegi/interp.(*Interpreter).EvalPath(0x140000f9b00, {0x16b8eb728, 0x17})
	/Users/marc/go/src/github.com/traefik/yaegi/interp/interp.go:508 +0xe8
main.runFile(0x140000f9b00, {0x16b8eb728, 0x17}, 0x0)
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:154 +0xb0
main.run({0x14000032050, 0x1, 0x1})
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/run.go:117 +0xe14
main.main()
	/Users/marc/go/src/github.com/traefik/yaegi/cmd/yaegi/yaegi.go:144 +0x384
```

### Yaegi Version

v0.11.0

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #1320 and #1294.

### CODE REVIEW

File: interp/run.go [hunk 1]
```diff
@@ -1125,55 +1125,69 @@ func methodByName(value reflect.Value, name string) reflect.Value {
...
 			for j := 0; j < numOut; j++ {
 				ind := c.findex + j
-				values = append(values, func(f *frame) reflect.Value { return f.data[ind] })
+				if !isInterfaceSrc(arg) || isEmptyInterface(arg) {
+					values = append(values, func(f *frame) reflect.Value { return f.data[ind] })
+					continue
+				}
+				values = append(values, func(f *frame) reflect.Value {
+					return reflect.ValueOf(valueInterface{value: f.data[ind]})
+				})
```
Comment (mpl) [inline interp/run.go:1175]: I think we should add a "break" statement after this line, because I've just realized that it is not possible to nest a function that returns more than one argument. Or maybe we should catch this earlier if NumOut is > 1.
For example, consider this (invalid) program:

```
package main

import (
	"errors"
)

func tworets() (string, error) {
	return "hello", errors.New("an error")
}

func takesfour(i int, s string, err error, ss string) {
	println(i)
	println(s)
	println(err)
	println(ss)
}

func main() {
	takesfour(7, tworets(), "world")
}
```

```
% go run ./sample.go 
# command-line-arguments
./sample.go:19:11: not enough arguments in call to takesfour
./sample.go:19:22: multiple-value tworets() in single-value context
% yaegi run ./sample.go 
run: ./sample.go:19:15: cannot use func() (string,error) as type string
```

So fortunately it looks like we also get an error in yaegi in that case, but I think adding a break here would make the intention clearer and would be safer anyway. WDYT?

or am I missing something?

File: interp/run.go [hunk 2]
```diff
@@ -1125,55 +1125,69 @@ func methodByName(value reflect.Value, name string) reflect.Value {
...
+			for j := range cc0.typ.ret {
 				ind := c.findex + j
-				values = append(values, func(f *frame) reflect.Value { return f.data[ind] })
+				if !isInterfaceSrc(arg) || isEmptyInterface(arg) {
+					values = append(values, func(f *frame) reflect.Value { return f.data[ind] })
+					continue
+				}
+				values = append(values, func(f *frame) reflect.Value {
+					return reflect.ValueOf(valueInterface{value: f.data[ind]})
+				})
```
Comment (mpl) [inline interp/run.go:1188]: same remark as above

File: interp/run.go (hunk 1 above)
Comment (mpl) [reply interp/run.go:1175]: I had forgotten about this legitimate case:

```
package main

func tworets() (string, int) {
	return "hello", 4
}

func takestwo(s string, i int) {
	println(s)
	println(i)
}

func main() {
	takestwo(tworets())
}
```

which is allowed because the number of arguments is exactly the same as the number of returned values.
But I've just tried and it still works with the breaks I proposed. And I think it is more efficient as it does less work.

Comment (mpl) [reply interp/run.go:1175]: nvm, I had misunderstood.

**Review by mpl — APPROVED** [review]
