### PR TITLE
interp: fix derivation of type of slice expression of binary object

### LINKED ISSUE #1328: slice expression
### The following program `sample.go` triggers an unexpected result

```go
package main

import (    
    "crypto/sha1"
    "encoding/hex"                                                                                    
)                    
                                      
func main() {                           
    script := "hello"                                                                                 
    sumRaw := sha1.Sum([]byte(script))                                                                
    sum := hex.EncodeToString(sumRaw[:])
    println(sum)
}
```

### Expected result

```console
$ go run ./sample.go
aaf4c61ddcc5e8a2dabede0f3b482cd9aea9434d
```

### Got

```console
yaegi ./sample.go 
run: ./sample.go:11:28: cannot use type [20]uint8 as type []uint8
```

### Yaegi Version

v0.11.1

### Additional Notes

_No response_

### PR DESCRIPTION
**Pull request by mvertes**
Fixes #1328.

### CODE REVIEW

File: interp/type.go [hunk 1]
```diff
@@ -854,8 +854,14 @@ func nodeType2(interp *Interpreter, sc *scope, n *node, seen []*node) (t *itype,
...
+		switch t.cat {
+		case ptrT:
 			t = t.val
+		case valueT:
+			switch t.rtype.Kind() {
+			case reflect.Array, reflect.Ptr:
+				t = valueTOf(reflect.SliceOf(t.rtype.Elem()), withScope(sc))
+			}
 		}
 		if t.cat == arrayT {
```
Comment (mpl) [inline interp/type.go:866]: this should be moved as a case within the newly introduced switch L857, no?

File: interp/type.go [hunk 2]
```diff
@@ -854,6 +854,13 @@ func nodeType2(interp *Interpreter, sc *scope, n *node, seen []*node) (t *itype,
 		if err != nil {
 			return nil, err
 		}
+
+		if t.cat == valueT {
+			switch t.rtype.Kind() {
+			case reflect.Array, reflect.Ptr:
+				t = valueTOf(reflect.SliceOf(t.rtype.Elem()), withScope(sc))
+			}
+		}
```
Comment (mpl) [inline interp/type.go:863]:
```suggestion
			break
		}
```

**Review by mpl — APPROVED** [review]

File: interp/type.go (hunk 1 above)
Comment (mpl) [reply interp/type.go]: nevermind, I was confused by the succesion of switch and if. both indeed need to be done.
