### PR TITLE
interp: parse circular interface definitions

### LINKED ISSUE #999: recursive interface with aliased type
`The` following program `sample.go` triggers an unexpected error:

```go
package main

import "fmt"

type I1 interface{ A }

type A = I2
    
type I2 interface{ F() I1 }
    
func main() {
    var i I1
    fmt.Println(i)
}
```

Expected result:
```console
$ go run ./sample.go
<nil>
```

Got:
```console
$ yaegi ./sample.go
./sample.go:5:6: constant definition loop
```

This is a simplified test case from what we see in #260 and #995.

### PR DESCRIPTION
**Pull request by mvertes**
An undefined type detection function has been added to better diagnose
incomplete type definitions. Implicit type names in interface or struct
declarations are now better handled. The incomplete status is not
fowarded to aliased type declarations to handle circular definitions.

Fixes #999 and #995. Improves #260 (goes farther, but still fails).

### CODE REVIEW

File: interp/type.go [hunk 1]
```diff
@@ -885,7 +888,13 @@ func isComplete(t *itype, visited map[string]bool) bool {
 		visited[name] = true
 	}
 	switch t.cat {
-	case aliasT, arrayT, chanT, chanRecvT, chanSendT, ptrT:
+	case aliasT:
```
Comment (mpl) [inline interp/type.go:891]: Sorry, because github is stupid, I have to comment here.

I believe L884-L886 can be simplified as:

```
if visited[name] {
   return true
}
```

File: interp/type.go [hunk 2]
```diff
@@ -885,7 +888,13 @@ func isComplete(t *itype, visited map[string]bool) bool {
...
+		if t.val != nil && t.val.incomplete && t.val.cat != nilT {
```
Comment (mpl) [inline interp/type.go:892]: If the aliased type is already complete, we also want to return true, right?
```suggestion
		if t.val != nil && t.val.cat != nilT {
```

File: interp/type.go [hunk 3]
```diff
@@ -899,6 +908,8 @@ func isComplete(t *itype, visited map[string]bool) bool {
 	case interfaceT, structT:
 		complete := true
 		for _, f := range t.field {
+			// Fiedld implicit type names must be marked as visited, to break false circles.
+			visited[f.typ.path+"/"+f.typ.name] = true
 			complete = complete && isComplete(f.typ, visited)
```
Comment (mpl) [inline interp/type.go:913]:
```suggestion
			complete &= isComplete(f.typ, visited)
```

File: interp/gta.go [hunk 4]
```diff
@@ -319,7 +319,56 @@ func (interp *Interpreter) gtaRetry(nodes []*node, importPath string) error {
...
+		for _, n := range revisit {
+			if n.kind == typeSpec {
+				if err := definedType(n.typ); err != nil {
+					return err
+				}
+			}
+		}
+		switch revisit[0].kind {
+		case typeSpec:
+			return revisit[0].cfgErrorf("incomplete type definition: %s", revisit[0].typ.name)
```
[the remark this answers is not in the document]
Comment (mvertes) [reply interp/gta.go:331]: The type could still be incomplete even if defined, if for example an array size is still undefined (constant undefined). But in that case, we should directly display "constant undefined" instead, so yes, you are right, something has to be changed here.

File: interp/type.go (hunk 3 above)
Comment (mvertes) [reply interp/type.go:913]: No! It's not equivalent.You are replacing a logical `and` where right side is not evaluated if left is false, with an arithmetic bitwise `and` (not boolean), where the operand is called unconditionally.

Comment (mpl) [reply interp/type.go:913]: indeed

**Review by mpl — APPROVED** [review]
